version: '2'

services:

  docker-av:
    image: ChanTingHui/anitVirusSTI
    container_name: docker-av
    # uncomment and set the email address to receive email alerts when viruses are detected
    command:
      - /usr/local/install_alerts.sh ctinghui38@gmail.com
    volumes:
      - ./data/queue:/data/av/queue
      - ./data/ok:/data/av/ok
      - ./data/nok:/data/av/nok
    #  - ./data/quarantine:/data/av/quarantine
    networks:
      - 192.168.116.133

networks:
  192.168.116.133: